# 全局服务请求路径前缀
server:
  port: 8080
  servlet.context-path: /tencent

spring:
  application:
    name: tencent
  profiles:
    active: prod
  # 连接池
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 8
      min-idle: 8
      max-active: 12
      # 获取连接等待超时时间
      max-wait: 60000
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      # 间隔多久进行一次检测，检测需要关闭的空闲连接
      time-between-eviction-runs-millis: 60000
      # 一个连接在池中最小生存的时间
      min-evictable-idle-time-millis: 300000
      # 打开 PSCache
      pool-prepared-statements: true
      # 并且指定每个连接上 PSCache 的大小
      max-pool-prepared-statement-per-connection-size: 20
      filters: config,stat,wall,slf4j
  #模板引擎
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    check-template-location: true
    suffix: .html
    encoding: UTF-8
    mode: HTML5

# mybatis
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  typeAliasesPackage: com.tencent.test.entity
  configuration:
    cache-enabled: false
    # 字段驼峰命名
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: AUTO
      # 表驼峰命名
      table-underline: true
      logic-not-delete-value: 0
      logic-delete-value: 1
      select-strategy: NOT_NULL
      insert-strategy: NOT_NULL
      update-strategy: NOT_NULL
    banner: false

task:
  getData:
    baseUrl: https://ke.qq.com/
    cron: 0 0 13 * * ?



